- include: configure_service.yml

- name: ZIP | Copy JBoss EAP zip file to {{ jboss_eap_download_dir }}
  copy:
    src: "{{ jboss_eap_zip_file }}"
    dest: "{{ jboss_eap_download_dir }}"
  when: jboss_eap_zip_file_url is not defined
  tags:
    - jboss_eap

- name: ZIP | Download zip file to {{ jboss_eap_download_dir }}
  get_url:
    url: "{{ jboss_eap_zip_file_url }}"
    dest: "{{ jboss_eap_download_dir }}"
  when: jboss_eap_zip_file_url is defined
  tags:
    - jboss_eap

- name: ZIP | Extract JBoss EAP zip file to {{ jboss_eap_library_dest }}
  unarchive:
    src: "{{ jboss_eap_download_dir }}/{{ jboss_eap_zip_file | basename }}"
    dest: "{{ jboss_eap_library_dest }}"
    copy: no
    creates: "{{ jboss_eap_jboss_home }}/version.txt"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: 0755
  register: jboss_install
  tags:
    - jbass_eap

- include: apply_patch.yml
  when: jboss_eap_patch
